### ISSUE TITLE
oom with larger marching cubes resolutions

### ISSUE THREAD

**Issue by kampelmuehler** [cvlab-epfl/MeshUDF#3]
Hi,

with `--MC 512` the `dense` array at 

https://github.com/cvlab-epfl/MeshUDF/blob/main/optimize_chamfer_A_to_B.py#L264

needs over 100 GB in memory and causes the execution to fail. Of course it works with `--no_smooth_borders``.

**Comment by EchoTHChen** [comment]
I also met this problem. How did you resolve it finally ?

**Comment by bguillard** [comment]
Hello, and thanks for pointing this out. This happens when smoothing border vertices on CPU. As pointed out by @kampelmuehler, a quick way to solve it is to disable border smoothing with ```--no_smooth_borders```.
I've otherwise pushed a version using a sparse array instead, which should be more memory-friendly. Feel free to try it out and comment!
